server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root #数据库用户
    password: mysql@password #数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-idle: 10
      min-idle: 5
      max-wait-millis: 1000
  redis: # Redis 配置
    database: 1 #数据库索引(默认为0)
    host: 127.0.0.1
    port: 6379 #默认链接端口
    password: "" #默认为空
    lettuce:
      pool:
        max-wait: -1 # 最大阻塞等待时间（使用负值没有限制）默认为 -1
        max-idle: 8  # 链接池中最大空闲连接 默认 8
        min-idle: 0
        max-active: 8
    timeout: 5000ms
    # 项目自定义配置

  myconfig:
      # swagger 的 enable 配置
      swagger-enable: true

mybatis:
  type-aliases-package: com.robin.studyweb.pojo
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true




