server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root #数据库用户
    password: mysql@password #数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-idle: 10
      min-idle: 5
      max-wait-millis: 1000
  redis: # Redis 配置
    database: 1 #数据库索引(默认为0)
    host: 127.0.0.1
    port: 6379 #默认链接端口
    password: "" #默认为空
    lettuce:
      pool:
        max-wait: -1 # 最大阻塞等待时间（使用负值没有限制）默认为 -1
        max-idle: 8  # 链接池中最大空闲连接 默认 8
        min-idle: 0
        max-active: 8
    timeout: 5000ms
  mail: # 邮箱配置
    host: smtp.163.com
    username: xuzhenshanvip@163.com
    password: LENJRGXMIRWKSWPK
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
        imap:
          ssl:
            socketFactory:
              fallback: false

  # 项目自定义配置
  myconfig:
    # swagger 的 enable 配置
    swagger-enable: true
    md5-salt: passwordsalt

mybatis:
  type-aliases-package: com.example.learnitem.dao
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





